spring:
  application:
    name: yf-mall-third-party
  cloud:
    alicloud:
      access-key: LTAI5t9h3q9zdF3U7At8HJJ7
      secret-key: F6BA9HiOyLz5Pch92L21VIjevq0vkZ
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 30000

yf:
  third:
    oss:
      bucket: yifang-mall
      host: https://yifang-mall.oss-cn-guangzhou.aliyuncs.com
