version: "3.9"

services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Shanghai
      # 指定环境变量LANG编码，否则初始化数据库表会乱码
      LANG: C.UTF-8
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/sql:/sql"
      - "./mysql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
    restart: always

  nacos:
    image: nacos/nacos-server:2.0.3
    env_file:
      - ./nacos/env/nacos-standlone-mysql.env
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always